export const notifications = [
  {
    id: 1,
    invitation_status: "pending",
    conference_id: 30,
    subject: "you are invited to review in conference",
    date_of_creation: "2022-05-30T23:42:32.794430Z",
    type: "invitation",
    request_to_edit_article_id: null,
  },
  {
    idd: 2,
    invitation_status: "pending",
    conference_id: 30,
    subject: "you are invited to review in conference",
    date_of_creation: "2022-05-30T23:42:32.794430Z",
    type: "invitationd",
    request_to_edit_article_id: null,
  },
  {
    idd: 3,
    invitation_status: "pending",
    conference_id: 30,
    subject: "you are invited to review in conference",
    date_of_creation: "2022-05-30T23:42:32.794430Z",
    type: "invitationd",
    request_to_edit_article_id: null,
  },
  {
    idd: 4,
    invitation_status: "pending",
    conference_id: 30,
    subject: "you are invited to review in conference",
    date_of_creation: "2022-05-30T23:42:32.794430Z",
    type: "invitation",
    request_to_edit_article_id: null,
  },
  {
    idd: 4,
    invitation_status: "pending",
    conference_id: 30,
    subject: "you are invited to review in conference",
    date_of_creation: "2022-05-30T23:42:32.794430Z",
    type: "invitation",
    request_to_edit_article_id: null,
  },
  {
    idd: 4,
    invitation_status: "pending",
    conference_id: 30,
    subject: "you are invited to review in conference",
    date_of_creation: "2022-05-30T23:42:32.794430Z",
    type: "invitation",
    request_to_edit_article_id: null,
  },
  {
    idd: 4,
    invitation_status: "pending",
    conference_id: 30,
    subject: "you are invited to review in conference",
    date_of_creation: "2022-05-30T23:42:32.794430Z",
    type: "invitation",
    request_to_edit_article_id: null,
  },
];
